CREATE TABLE IF NOT EXISTS Addresses (
  AddressID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Country VARCHAR(60) NOT NULL,
  State VARCHAR(50) NOT NULL,
  Suburb VARCHAR(50) NOT NULL,
  Zipcode VARCHAR(10) NOT NULL,
  Address VARCHAR(80) NOT NULL,
  PRIMARY KEY (AddressID)
);

CREATE TABLE IF NOT EXISTS Accounts (
  AccountID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AddressID MEDIUMINT UNSIGNED,
  Enabled BOOLEAN NOT NULL DEFAULT 1,
  PermGroup TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FailCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PassHash VARCHAR(64) NOT NULL DEFAULT '',
  RealName VARCHAR(50) NOT NULL DEFAULT '',
  Email varchar(50) NOT NULL DEFAULT '',
  Phone VARCHAR(20) NOT NULL DEFAULT '',
  Settings TINYTEXT,
  LastIP TINYTEXT,
  LastTime DATETIME,
  Created DATETIME,
  PRIMARY KEY (AccountID),
  UNIQUE KEY (Email),
  FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);

CREATE TABLE IF NOT EXISTS Orders (
  OrderID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AccountID MEDIUMINT UNSIGNED NOT NULL,
  Status VARCHAR(50) DEFAULT 'Unconfirmed',
  ShipStatus VARCHAR(50) DEFAULT 'Processing',
  Shipping DECIMAL(18,8) NOT NULL,
  Total DECIMAL(18,8) NOT NULL,
  Amount DECIMAL(18,8) NOT NULL DEFAULT 0,
  Currency VARCHAR(5) NOT NULL DEFAULT '',
  Cart VARCHAR(500) NOT NULL,
  Note VARCHAR(500),
  KeyData VARCHAR(500),
  Code VARCHAR(32),
  Address TINYTEXT,
  TranCode TINYTEXT,
  DatePaid DATETIME,
  Created DATETIME,
  PRIMARY KEY (OrderID),
  FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);

CREATE TABLE IF NOT EXISTS Vouchers (
  VouchID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ItemID MEDIUMINT UNSIGNED NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Discount DECIMAL(12,4) NOT NULL,
  Enabled BOOLEAN NOT NULL DEFAULT 1,
  Target BOOLEAN NOT NULL DEFAULT 0,
  UseType TINYINT NOT NULL DEFAULT 0,
  Credits INT UNSIGNED NOT NULL,
  CodeData VARCHAR(64) NOT NULL,
  PRIMARY KEY (VouchID),
  UNIQUE KEY (CodeData)
);

CREATE TABLE IF NOT EXISTS BtcAdds (
  AddID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Address VARCHAR(50) NOT NULL,
  Enabled BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (AddID),
  UNIQUE KEY (Address)
);

ALTER TABLE Products 
ADD FileVoteSum INT UNSIGNED NOT NULL DEFAULT 0 AFTER FileVotes,
ADD FileVoteNum INT UNSIGNED NOT NULL DEFAULT 0 AFTER FileVoteSum;

ALTER TABLE Codes 
ADD OrderID INT UNSIGNED NOT NULL AFTER ItemID,
ADD AccountID INT UNSIGNED NOT NULL AFTER OrderID;

DROP TRIGGER IF EXISTS Orders_OnInsert;
CREATE TRIGGER Orders_OnInsert BEFORE INSERT ON Orders
FOR EACH ROW SET NEW.Created = IFNULL(NEW.Created, UTC_TIMESTAMP());

DROP TRIGGER IF EXISTS Accounts_OnInsert;
CREATE TRIGGER Accounts_OnInsert BEFORE INSERT ON Accounts
FOR EACH ROW SET NEW.Created = IFNULL(NEW.Created, UTC_TIMESTAMP());